FROM node:14-alpine3.17

# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Dependencies
COPY package.json .

# Copy app source code
COPY . .

#RUN npm install
RUN npm install

# Build the React app
#RUN npm run build


# Exports

EXPOSE 3000

# Set up a default command
CMD [ "npm", "start" ]