# Assuming you're using a Node.js base image
FROM node:14.16-alpine

# Install nodemon
RUN npm install -g nodemon

# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Dependencies
COPY package.json .
#COPY package-lock.json /usr/src/app/

# Install other dependencies
RUN npm install

# Copy app source code
COPY . .

# Exports
EXPOSE 3001

# Set up a default command
CMD ["nodemon", "index.js"]
